angular.module('mapplicPlugin', [])
    .directive('mapplicPlugin',function($compile,$timeout){
        return{restrict: 'A', transclude: true,
            link: function (scope, home, attrs){
                $('#home').mapplic({
                  source: 'json/cmu.json',
                  height: 750,
                  sidebar: false,  
                  locations: true, 
                  fullscreen:false, 
                  categories:true,
                  minimap:false,
                  locations:true,
                  hovertip: true,
                  developer: true,
                  maxscale: 6,
                  zoom:true,
                });
               
                //Routing 
                  //Main Gate
                    $('#mg-adm').mapplic({
                      source: 'json/routing/mg-routes/mg-admin.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                    });
                    $('#mg-cas-m').mapplic({
                      source: 'json/routing/mg-routes/mg-cas-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                    });
                    $('#mg-coa-m').mapplic({
                      source: 'json/routing/mg-routes/mg-coa-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                    });
                    $('#mg-cbm-m').mapplic({
                      source: 'json/routing/mg-routes/mg-cbm-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                    });
                    $('#mg-coed-m').mapplic({
                      source: 'json/routing/mg-routes/mg-coed-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                    });
                     $('#mg-coeng-m').mapplic({
                      source: 'json/routing/mg-routes/mg-coeng-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                    });
                    $('#mg-cfes-m').mapplic({
                      source: 'json/routing/mg-routes/mg-cfes-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                    });
                   
                    $('#mg-che-m').mapplic({
                      source: 'json/routing/mg-routes/mg-che-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                    });
                    $('#mg-con-m').mapplic({
                      source: 'json/routing/mg-routes/mg-con-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                    });
                    $('#mg-cvm-m').mapplic({
                      source: 'json/routing/mg-routes/mg-cvm-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                    });
                  //Agriculture
                     $('#coa-adm').mapplic({
                      source: 'json/routing/coa-routes/coa-adm.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                      });
                        $('#coa-cas-m').mapplic({
                        source: 'json/routing/coa-routes/coa-cas-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                         $('#coa-cbm-m').mapplic({
                        source: 'json/routing/coa-routes/coa-cbm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#coa-coed-m').mapplic({
                        source: 'json/routing/coa-routes/coa-coed-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coa-coe-m').mapplic({
                        source: 'json/routing/coa-routes/coa-coe-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#coa-cfes-m').mapplic({
                        source: 'json/routing/coa-routes/coa-cfes-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coa-che-m').mapplic({
                        source: 'json/routing/coa-routes/coa-che-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                        $('#coa-con-m').mapplic({
                        source: 'json/routing/coa-routes/coa-con-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coa-cvm-m').mapplic({
                        source: 'json/routing/coa-routes/coa-cvm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                  //ARTS AND SCIENCES
                     $('#cas-admin').mapplic({
                      source: 'json/routing/cas-routes/cas-admin.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                        });  
                       $('#cas-coa-m').mapplic({
                        source: 'json/routing/cas-routes/cas-coa-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      }); 
                      $('#cas-cbm-m').mapplic({
                        source: 'json/routing/cas-routes/cas-cbm-m.json',
                        height: 500, 
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cas-coed-m').mapplic({
                        source: 'json/routing/cas-routes/cas-coed-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cas-coe-m').mapplic({
                        source: 'json/routing/cas-routes/cas-coe-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                        $('#cas-cfes-m').mapplic({
                        source: 'json/routing/cas-routes/cas-cfes-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                        $('#cas-che-m').mapplic({
                        source: 'json/routing/cas-routes/cas-che-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cas-con-m').mapplic({
                        source: 'json/routing/cas-routes/cas-con-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cas-cvm-m').mapplic({
                        source: 'json/routing/cas-routes/cas-cvm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                  //Business Management
                      $('#cbm-admin').mapplic({
                      source: 'json/routing/cbm-routes/cbm-admin.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                      });
                      $('#cbm-cas-m').mapplic({
                        source: 'json/routing/cbm-routes/cbm-cas-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cbm-coa-m').mapplic({
                        source: 'json/routing/cbm-routes/cbm-coa-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#cbm-coe-m').mapplic({
                        source: 'json/routing/cbm-routes/cbm-coe-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });    
                      $('#cbm-coed-m').mapplic({
                        source: 'json/routing/cbm-routes/cbm-coed-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#cbm-cfes-m').mapplic({
                        source: 'json/routing/cbm-routes/cbm-cfes-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });     
                       $('#cbm-che-m').mapplic({
                        source: 'json/routing/cbm-routes/cbm-che-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cbm-con-m').mapplic({
                        source: 'json/routing/cbm-routes/cbm-con-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });   
                      $('#cbm-cvm-m').mapplic({
                        source: 'json/routing/cbm-routes/cbm-cvm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                  //Engineering
                      $('#coe-admin').mapplic({
                        source: 'json/routing/coe-routes/coe-admin.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                        });
                       $('#coe-cas-m').mapplic({
                        source: 'json/routing/coe-routes/coe-cas-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coe-cbm-m').mapplic({
                        source: 'json/routing/coe-routes/coe-cbm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coe-coa-m').mapplic({
                        source: 'json/routing/coe-routes/coe-coa-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coe-coed-m').mapplic({
                        source: 'json/routing/coe-routes/coe-coed-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      }); 
                      $('#coe-cfes-m').mapplic({
                        source: 'json/routing/coe-routes/coe-cfes-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coe-che-m').mapplic({
                        source: 'json/routing/coe-routes/coe-che-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coe-con-m').mapplic({
                        source: 'json/routing/coe-routes/coe-con-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coe-cvm-m').mapplic({
                        source: 'json/routing/coe-routes/coe-cvm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                  //Education
                      $('#coed-admin').mapplic({
                        source: 'json/routing/coed-routes/coed-admin.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coed-coa-m').mapplic({
                        source: 'json/routing/coed-routes/coed-coa-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coed-cas-m').mapplic({
                        source: 'json/routing/coed-routes/coed-cas-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                        $('#coed-cbm-m').mapplic({
                        source: 'json/routing/coed-routes/coed-cbm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#coed-coe-m').mapplic({
                        source: 'json/routing/coed-routes/coed-coe-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });  
                       $('#coed-cfes-m').mapplic({
                        source: 'json/routing/coed-routes/coed-cfes-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      }); 
                       $('#coed-che-m').mapplic({
                        source: 'json/routing/coed-routes/coed-che-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#coed-con-m').mapplic({
                        source: 'json/routing/coed-routes/coed-con-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#coed-cvm-m').mapplic({
                        source: 'json/routing/coed-routes/coed-cvm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                  //Forestry
                     $('#cfes-admin').mapplic({
                      source: 'json/routing/cfes-routes/cfes-admin.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                     });
                     $('#cfes-coa-m').mapplic({
                      source: 'json/routing/cfes-routes/cfes-coa-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                     });
                     $('#cfes-cas-m').mapplic({
                      source: 'json/routing/cfes-routes/cfes-cas-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                     });
                     $('#cfes-cbm-m').mapplic({
                      source: 'json/routing/cfes-routes/cfes-cbm-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                     });
                     $('#cfes-coe-m').mapplic({
                      source: 'json/routing/cfes-routes/cfes-coe-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                     });
                     $('#cfes-coed-m').mapplic({
                      source: 'json/routing/cfes-routes/cfes-coed-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                     });
                     $('#cfes-che-m').mapplic({
                      source: 'json/routing/cfes-routes/cfes-che-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                     });
                     $('#cfes-con-m').mapplic({
                      source: 'json/routing/cfes-routes/cfes-con-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                     });
                     $('#cfes-cvm-m').mapplic({
                      source: 'json/routing/cfes-routes/cfes-cvm-m.json',
                      height: 500,
                      sidebar: false,
                      locations: true,
                      fullscreen:false,
                      categories:true,
                      minimap:false,
                      hovertip: true,
                      developer: true,
                      maxscale: 4,
                      zoom:true,
                      });
                  //Human Ecology
                      $('#che-admin').mapplic({
                        source: 'json/routing/che-routes/che-admin.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                        });
                      $('#che-coa-m').mapplic({
                        source: 'json/routing/che-routes/che-coa-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                        });
                      $('#che-cas-m').mapplic({
                          source: 'json/routing/che-routes/che-cas-m.json',
                          height: 500,
                          sidebar: false,
                          locations: true,
                          fullscreen:false,
                          categories:true,
                          minimap:false,
                          hovertip: true,
                          developer: true,
                          maxscale: 4,
                          zoom:true,
                      });
                      $('#che-coed-m').mapplic({
                        source: 'json/routing/che-routes/che-coed-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                        });
                      $('#che-coe-m').mapplic({
                        source: 'json/routing/che-routes/che-coe-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                        });
                      $('#che-cvm-m').mapplic({
                        source: 'json/routing/che-routes/che-cvm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                        });
                      $('#che-con-m').mapplic({
                        source: 'json/routing/che-routes/che-con-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#che-cbm-m').mapplic({
                        source: 'json/routing/che-routes/che-cbm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#che-cfes-m').mapplic({
                        source: 'json/routing/che-routes/che-cfes-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                  //Nursing
                      $('#con-admin').mapplic({
                        source: 'json/routing/con-routes/con-admin.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#con-coa-m').mapplic({
                        source: 'json/routing/con-routes/con-coa-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#con-cas-m').mapplic({
                        source: 'json/routing/con-routes/con-cas-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#con-cbm-m').mapplic({
                        source: 'json/routing/con-routes/con-cbm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#con-coe-m').mapplic({
                        source: 'json/routing/con-routes/con-coe-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#con-coed-m').mapplic({
                        source: 'json/routing/con-routes/con-coed-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#con-cfes-m').mapplic({
                        source: 'json/routing/con-routes/con-cfes-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#con-che-m').mapplic({
                        source: 'json/routing/con-routes/con-che-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                        $('#con-cvm-m').mapplic({
                        source: 'json/routing/con-routes/con-cvm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                  //VetMed
                      $('#cvm-admin').mapplic({
                        source: 'json/routing/cvm-routes/cvm-admin.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#cvm-coa-m').mapplic({
                        source: 'json/routing/cvm-routes/cvm-coa-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cvm-cas-m').mapplic({
                        source: 'json/routing/cvm-routes/cvm-cas-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cvm-cbm-m').mapplic({
                        source: 'json/routing/cvm-routes/cvm-cbm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cvm-coe-m').mapplic({
                        source: 'json/routing/cvm-routes/cvm-coe-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cvm-coed-m').mapplic({
                        source: 'json/routing/cvm-routes/cvm-coed-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cvm-cfes-m').mapplic({
                        source: 'json/routing/cvm-routes/cvm-cfes-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                       $('#cvm-che-m').mapplic({
                        source: 'json/routing/cvm-routes/cvm-che-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                        $('#cvm-con-m').mapplic({
                        source: 'json/routing/cvm-routes/cvm-con-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                  //Market
                      $('#market-coa-m').mapplic({
                        source: 'json/routing/market-routes/market-coa-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#market-cas-m').mapplic({
                        source: 'json/routing/market-routes/market-cas-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#market-cbm-m').mapplic({
                        source: 'json/routing/market-routes/market-cbm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#market-cfes-m').mapplic({
                        source: 'json/routing/market-routes/market-cfes-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#market-che-m').mapplic({
                        source: 'json/routing/market-routes/market-che-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#market-coe-m').mapplic({
                        source: 'json/routing/market-routes/market-coe-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#market-coed-m').mapplic({
                        source: 'json/routing/market-routes/market-coed-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#market-con-m').mapplic({
                        source: 'json/routing/market-routes/market-con-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                      $('#market-cvm-m').mapplic({
                        source: 'json/routing/market-routes/market-cvm-m.json',
                        height: 500,
                        sidebar: false,
                        locations: true,
                        fullscreen:false,
                        categories:true,
                        minimap:false,
                        hovertip: true,
                        developer: true,
                        maxscale: 4,
                        zoom:true,
                      });
                $timeout(function(){}, 1000);               
            }            
        };
    });    